[package]
name = "rust-blaster"
version = "0.1.0"
authors = ["katagis <fox.dealos@gmail.com>"]
edition = "2018"

[dependencies]
ggez = { path = "../ggez" }
rand = "0.6.5"
serde = { version = "1.0.91", features = ["derive"] }
serde_json = "1.0"
bincode = "1.1.4"
